# Base image
FROM node:18-alpine as development

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
CMD [ "npm", "run", "start:dev" ]

# # Base image
# FROM node:18-alpine as production

# WORKDIR /usr/src/app
# COPY package*.json ./
# RUN npm install
# COPY . .
# RUN npm run build
# CMD [ "node", "dist/main.js" ]